SyncLounge documentation
GhostWriters/DockSTARTer.com pull request #89
Opened 2020-02-28 04:20 UTC by MagicalCodeMonkey

Figuring out some of this was very dependent on [this comment](https://github.com/samcm/synclounge/issues/125#issuecomment-578373503) as well as monitoring the development console for issues.

See https://github.com/GhostWriters/DockSTARTer/pull/875 for the corresponding app PR.

2020-02-28 19:17 UTC, nemchik requested changes
I think it would make sense to submit a PR to https://github.com/linuxserver/reverse-proxy-confs with a proxy for synclounge. I also think this one might need a bit of work. Specifically the proxy example here seems to be a subdomain proxy but is using a base url for some things. To simplify things it would make more sense to separate a subfolder and subdomain proxy (or skip the subfolder proxy if it's problematic).

2020-03-03 20:50 UTC, MagicalCodeMonkey commented
PR in LSIO reverse-proxy-confs: https://github.com/linuxserver/reverse-proxy-confs/pull/136

I will update this documentation soon to reflect that

2020-03-06 18:46 UTC, MagicalCodeMonkey commented
PRs in SyncLounge to:
- Resolve some issues with the webapp. including the webroot issues: https://github.com/samcm/synclounge/pull/133
- Make some updates to how settings are handled to follow with ENV best practices: https://github.com/samcm/synclounge/pull/132

2020-05-11 20:14 UTC, nemchik approved these changes

2020-05-11 20:15 UTC, merged